image: 
  name: bamapps/bamweb-runtime-aws:0.0.2

pipelines:
  default:
    - step:
        name: Build
        services:
          - docker
        script:
          - ./login docker
          - ./build docker
          - ./push docker test
    - step:
        name: Deploy Test
        services:
          - docker
        script:
          - ./deploy docker test
    - step:
        name: Test
        services:
          - docker
        script:
          - ./test pipeline dev
    - step:
        name: Deploy Staging
        trigger: manual
        services:
          - docker
        script: 
          - ./deploy docker staging  
  branches:
    master:
      - step:
        name: Build
        services:
          - docker
        script:
          - ./login docker
          - ./build docker
          - ./push docker release
      - step:
          name: Test
          services:
            - docker
          script:
            - ./test pipeline smoke
      - step:
        name: Deploy Staging
        trigger: manual
        services:
          - docker
        script: 
          - ./deploy docker staging 
      - step:
          name: Deploy Release
          trigger: manual
          services:
            - docker
          script: 
            - ./deploy docker release    