image: microsoft/dotnet:sdk

pipelines:
  default:
    - step:
        name: Build
        services:
          - docker
        script:
          - ./docker-login.sh
          - ./build.sh
          - ./docker-push-test.sh
    - step:
        name: Deploy Test
        services:
          - docker
        script:
          - ./deploy.sh test
    - step:
        name: Test
        services:
          - docker
        script:
          - ./test.sh
  branches:
    master:
      - step:
          name: Build
          services:
            - docker
          script:
            - source ./env.sh
            - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            - ./build.sh
            - ./docker-push-release.sh
      - step:
          name: Test
          services:
            - docker
          script:
            - ./test.sh
      - step:
          name: Deploy Release
          services:
            - docker
          script: 
            - ./deploy.sh release    