#!/bin/bash

if [[ $1 = "-help" ]] || [[ $1 = "-?" ]] || [[ $1 = "-h" ]]; then
    printf "usage: push <implementation> [additional arguments]\r\n"
    printf "\r\n"
    printf "Call push for the specified implementation flow; the default is 'docker'.\r\n"
    printf "Possible implementation values are found in the ./ci directory.\r\n"
    printf "\r\n"
    printf "Additional arguments:\r\n"
    printf "\tdocker - [ test | staging | release ] [ azure | dockerhub | amazon ]\r\n"
    printf "\r\n"
    exit 0
fi

IMPL=$1

if [[ -z $1 ]]; then
    export IMPL="docker"
fi

export COMMAND="push"

if [[ !(-z $2) ]]; then
    export COMMAND="push-$2"
fi

REGISTRYALIASORPATH=$3

if [[ -z $REGISTRYALIASORPATH ]]; then
    export REGISTRYALIASORPATH=$(<defaultimageregistry)
fi

printf "REGISTRYALIASORPATH is ${REGISTRYALIASORPATH}\r\n"
cd ./ci
./exec.sh ${IMPL} ${COMMAND} ${REGISTRYALIASORPATH}
cd ..
