apiVersion: v1
kind: Service
metadata:
  name: vimly-admin
  namespace: vimly-admin
  labels:
    app: vimly-admin
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: vimly-admin